### ISSUE TITLE
clubs,country dropdown

### ISSUE THREAD

**Issue by nelson360** [ChessCom/frontend-tdd-test#18]
in clubs ,countries drop down section there is ommission of ivory coast ,kindly update

**Comment by nelson360** [comment]
Ivory coast === Cote D'Ivoire

**Comment by proplunger** [comment]
Is anyone working on this issue?, I am open to help.

**Comment by martynchamberlin** [comment]
Closing as irrelevant to this repo, thanks. If this is a feature you'd like to see for Chess.com, please report a bug here: https://support.chess.com/category/146-report-a-bug
